#ifndef RENDER_HPP
#define RENDER_HPP
#include "Merlin/Render/buffer_layout.hpp"
#include "Merlin/Render/camera.hpp"
#include "Merlin/Render/frame_buffer.hpp"
#include "Merlin/Render/graphics_context.hpp"
#include "Merlin/Render/index_buffer.hpp"
#include "Merlin/Render/lighting.hpp"
#include "Merlin/Render/perspective_camera.hpp"
#include "Merlin/Render/render_api.hpp"
#include "Merlin/Render/renderer.hpp"
#include "Merlin/Render/shader.hpp"
#include "Merlin/Render/texture2d.hpp"
#include "Merlin/Render/transform.hpp"
#include "Merlin/Render/vertex_array.hpp"
#include "Merlin/Render/vertex_buffer.hpp"
#include "Merlin/Render/mesh.hpp"
#include "Merlin/Render/mesh_vertex.hpp"
#endif
